### ISSUE TITLE
Изучение GP Regression

### ISSUE THREAD

**Issue by Edyarich** [intsystems/CreationOfIntelligentSystems_EEG_23#2]
## DONE
- 10, 11
- ...

## TODO
- пункты 7 - 10 из раздела РАБОТЫ
- ...

**Comment by PavelBartenev** [comment]
10-11 done

**Comment by PavelBartenev** [comment]
Прочитаны статьи: An Intuitive Tutorial to Gaussian Processes Regression
Jie Wang, Gaussian Processes in Machine Learning
Carl Edward Rasmussen, в которых представлен обзор методов регрессии на основе гауссовских процессов
